source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'pg'
gem 'devise'
gem 'haml-rails'
gem 'jquery-rails'
gem 'sass'
gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'
gem 'uglifier', '>= 1.0.3'
gem 'bootstrap-sass'
gem 'pry'
gem 'simple_form'
gem 'heroku'
gem 'rqrcode-rails3'
gem 'thin'
gem 'factory_girl_rails'

group :test, :development do
  gem 'rspec-rails'
  gem 'mocha'
  gem 'factory_girl_rails'
  gem 'forgery'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'mailcatcher'
end

gem 'passbook', :git => 'git://github.com/lgleasain/passbook.git'
